trigger:
- none

resources:
- repo: self

variables:
  containerRegistry: 'samplecontainer8899.azurecr.io'
  dockerRegistryServiceConnection: 'af96df78-8263-4dba-bb43-5ad37206afce'
  baseImageName: 'chatbot-base'
  appImageName: 'chatbot'
  aksClusterName: 'samplecluster89'
  aksSubscriptionEndpoint: 'Azure for Students'
  tag: 'latest'


stages:
- stage: BuildAndPushBaseImage
  displayName: 'Build and Push Base Image'
  jobs:  
  - job: BuildBaseImage
    displayName: 'Build Base Image'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build and push base image to container registry'
      inputs:
        command: 'buildAndPush'
        repository: '$(baseImageName)'
        dockerfile: '$(Build.SourcesDirectory)/base.Dockerfile'
        containerRegistry: '$(dockerRegistryServiceConnection)'
        tags: 'latest'

- stage: BuildAndPushAppImage
  displayName: 'Build and Push App Image'
  jobs:
  - job: BuildAppImage
    displayName: 'Build Application Image'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build and push application image to container registry'
      inputs:
        command: 'buildAndPush'
        repository: '$(appImageName)'
        dockerfile: '$(Build.SourcesDirectory)/chatbot.Dockerfile'
        containerRegistry: '$(dockerRegistryServiceConnection)'
        tags: 'latest'

- stage: Deploy
  displayName: 'Deploy stage'
  dependsOn: 
  - BuildAndPushBaseImage
  - BuildAndPushAppImage
  jobs:
  - deployment: Deploy
    displayName: 'Deploy'
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'myrepo.kube-node-lease' 
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self 
          - task: KubernetesManifest@0
            displayName: 'Deploy to Kubernetes cluster'
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'k8sserviceconnection'
              namespace: 'kube-node-lease'
              manifests: |
                $(Build.SourcesDirectory)/manifests/deployment.yml
                $(Build.SourcesDirectory)/service.yml
              containers: 'samplecontainer8899.azurecr.io/chatbot:latest'
              imagePullSecrets: 'imagepullsecret'
              rolloutStatusTimeout: '300'
